### ISSUE TITLE
Please clarify relationship with original repository

### ISSUE THREAD

**Issue by 0x80** [nlevo/redis-memoizer#1]
It is confusing to find different libraries that are clearly based on the same codebase without any mention of it. People have to waste time looking for differences and figuring out which one to use. 

I am assuming this repo was created because the original one was not maintained anymore? Please add a note at the top of the readme explaining this for people like me.

**Comment by nlevo** [comment]
README.md has been updated.

This repo is a copy of https://www.npmjs.com/package/redis-memoizer @ v1.0.2.
It was created due to the original repo being no longer available at the time of the creation of this repo.

**Comment by 0x80** [comment]
Thanks!
